--- #YAML:1.0
name:                WebService-Telnic
version:             0.2
abstract:            Interface to Telnic's SOAP API's
license:             mit
author:              
    - Peter Makholm <peter@makholm.net>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    List::Util:                    0
    LWP::UserAgent:                0
    Net::DNS::RR:                  0
    Scalar::Util:                  0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
